### ISSUE TITLE
audio normalize function diff with wavtokenzier

### ISSUE THREAD

**Issue by hertz-pj** [youngsheen/SimVQ#10]
In wavtokenizer, normalization is done as follows:
```
    #gain = np.random.uniform(-1, -6) if self.NAME == "train" else -3
    #waveform, _ = torchaudio.sox_effects.apply_effects_tensor(waveform, self.sample_rate, [["norm", f"{gain:.2f}"]])
```
However, in this work, it changed to:
```
if self.audio_normalize:
    mono = x.mean(dim=1, keepdim=True)
    volume = mono.pow(2).mean(dim=2, keepdim=True).sqrt()
    scale = 1e-8 + volume
    x = x / scale
    scale = scale.view(-1, 1)
else:
    scale = None
```
Could you explain the considerations behind this change? Has there been a comparison to determine which method is better?

**Comment by youngsheen** [comment]
The torchaudio.sox_effects.apply_effects_tensor function is used for data augmentation in wavtokenizer, which I believe would help improve performance. However, we did not utilize this function in SimVQ.

Additionally, the audio_normalize function is not used in either the wavtokenizer or SimVQ implementations.
